4.times do
  sample :ambi_lunar_land
  sample :ambi_drone
  play 36
  play 48
  sample :ambi_lunar_land
  sleep 1
  play 48
  sleep 0.5
  play 36
  sample :ambi_drone
  sleep 1
  play 36
  use_synth :saw
  play 38
  sleep 0.25
  play 50
  sleep 0.25
  play 62
  use_synth :saw
  play 38
  sleep 0.25
  play 50
  sleep 0.25
  play 38
  sleep 0.25
  play 50
  sleep 0.25
  play 62 
  sample :ambi_lunar_land
  play 48
  sample :ambi_lunar_land
  sample :ambi_drone
  sample :ambi_lunar_land
  sleep 1
  play 48
  sleep 0.5
  play 36
  sample :ambi_drone
  sleep 1
  play 36
  sample :ambi_glass_hum
  sample :ambi_haunted_hum
  sample :ambi_dark_woosh
end
